/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSearchRouteImport } from './routes/_dashboard/search'
import { Route as DashboardSafetyRouteImport } from './routes/_dashboard/safety'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardPeopleRouteImport } from './routes/_dashboard/people'
import { Route as DashboardNotificationRouteImport } from './routes/_dashboard/notification'
import { Route as DashboardMarketRouteImport } from './routes/_dashboard/market'
import { Route as DashboardInstallRouteImport } from './routes/_dashboard/install'
import { Route as DashboardFeedRouteImport } from './routes/_dashboard/feed'
import { Route as AuthWaitlistRouteImport } from './routes/_auth/waitlist'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthGuidelinesRouteImport } from './routes/_auth/guidelines'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as AuthFeaturesRouteImport } from './routes/_auth/features'
import { Route as AuthContactRouteImport } from './routes/_auth/contact'
import { Route as DashboardMessagesRouteRouteImport } from './routes/_dashboard/messages/route'
import { Route as DashboardMessagesIndexRouteImport } from './routes/_dashboard/messages/index'
import { Route as DashboardMessagesIdRouteImport } from './routes/_dashboard/messages/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSafetyRoute = DashboardSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPeopleRoute = DashboardPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationRoute = DashboardNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInstallRoute = DashboardInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFeedRoute = DashboardFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthWaitlistRoute = AuthWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGuidelinesRoute = AuthGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFeaturesRoute = AuthFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContactRoute = AuthContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardMessagesRouteRoute = DashboardMessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesIndexRoute = DashboardMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMessagesRouteRoute,
} as any)
const DashboardMessagesIdRoute = DashboardMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMessagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/messages': typeof DashboardMessagesRouteRouteWithChildren
  '/contact': typeof AuthContactRoute
  '/features': typeof AuthFeaturesRoute
  '/forgot': typeof AuthForgotRoute
  '/guidelines': typeof AuthGuidelinesRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/waitlist': typeof AuthWaitlistRoute
  '/feed': typeof DashboardFeedRoute
  '/install': typeof DashboardInstallRoute
  '/market': typeof DashboardMarketRoute
  '/notification': typeof DashboardNotificationRoute
  '/people': typeof DashboardPeopleRoute
  '/profile': typeof DashboardProfileRoute
  '/safety': typeof DashboardSafetyRoute
  '/search': typeof DashboardSearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof AuthIndexRoute
  '/messages/$id': typeof DashboardMessagesIdRoute
  '/messages/': typeof DashboardMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/contact': typeof AuthContactRoute
  '/features': typeof AuthFeaturesRoute
  '/forgot': typeof AuthForgotRoute
  '/guidelines': typeof AuthGuidelinesRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/waitlist': typeof AuthWaitlistRoute
  '/feed': typeof DashboardFeedRoute
  '/install': typeof DashboardInstallRoute
  '/market': typeof DashboardMarketRoute
  '/notification': typeof DashboardNotificationRoute
  '/people': typeof DashboardPeopleRoute
  '/profile': typeof DashboardProfileRoute
  '/safety': typeof DashboardSafetyRoute
  '/search': typeof DashboardSearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof AuthIndexRoute
  '/messages/$id': typeof DashboardMessagesIdRoute
  '/messages': typeof DashboardMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_dashboard/messages': typeof DashboardMessagesRouteRouteWithChildren
  '/_auth/contact': typeof AuthContactRoute
  '/_auth/features': typeof AuthFeaturesRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/guidelines': typeof AuthGuidelinesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/waitlist': typeof AuthWaitlistRoute
  '/_dashboard/feed': typeof DashboardFeedRoute
  '/_dashboard/install': typeof DashboardInstallRoute
  '/_dashboard/market': typeof DashboardMarketRoute
  '/_dashboard/notification': typeof DashboardNotificationRoute
  '/_dashboard/people': typeof DashboardPeopleRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/safety': typeof DashboardSafetyRoute
  '/_dashboard/search': typeof DashboardSearchRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_dashboard/messages/$id': typeof DashboardMessagesIdRoute
  '/_dashboard/messages/': typeof DashboardMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/messages'
    | '/contact'
    | '/features'
    | '/forgot'
    | '/guidelines'
    | '/login'
    | '/onboarding'
    | '/waitlist'
    | '/feed'
    | '/install'
    | '/market'
    | '/notification'
    | '/people'
    | '/profile'
    | '/safety'
    | '/search'
    | '/settings'
    | '/'
    | '/messages/$id'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/features'
    | '/forgot'
    | '/guidelines'
    | '/login'
    | '/onboarding'
    | '/waitlist'
    | '/feed'
    | '/install'
    | '/market'
    | '/notification'
    | '/people'
    | '/profile'
    | '/safety'
    | '/search'
    | '/settings'
    | '/'
    | '/messages/$id'
    | '/messages'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/privacy'
    | '/terms'
    | '/_dashboard/messages'
    | '/_auth/contact'
    | '/_auth/features'
    | '/_auth/forgot'
    | '/_auth/guidelines'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/waitlist'
    | '/_dashboard/feed'
    | '/_dashboard/install'
    | '/_dashboard/market'
    | '/_dashboard/notification'
    | '/_dashboard/people'
    | '/_dashboard/profile'
    | '/_dashboard/safety'
    | '/_dashboard/search'
    | '/_dashboard/settings'
    | '/_auth/'
    | '/_dashboard/messages/$id'
    | '/_dashboard/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/search': {
      id: '/_dashboard/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/safety': {
      id: '/_dashboard/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof DashboardSafetyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/people': {
      id: '/_dashboard/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof DashboardPeopleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notification': {
      id: '/_dashboard/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof DashboardNotificationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/market': {
      id: '/_dashboard/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/install': {
      id: '/_dashboard/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof DashboardInstallRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/feed': {
      id: '/_dashboard/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof DashboardFeedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/waitlist': {
      id: '/_auth/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthWaitlistRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/guidelines': {
      id: '/_auth/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof AuthGuidelinesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/features': {
      id: '/_auth/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthFeaturesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contact': {
      id: '/_auth/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthContactRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/messages': {
      id: '/_dashboard/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof DashboardMessagesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/messages/': {
      id: '/_dashboard/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof DashboardMessagesIndexRouteImport
      parentRoute: typeof DashboardMessagesRouteRoute
    }
    '/_dashboard/messages/$id': {
      id: '/_dashboard/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof DashboardMessagesIdRouteImport
      parentRoute: typeof DashboardMessagesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthContactRoute: typeof AuthContactRoute
  AuthFeaturesRoute: typeof AuthFeaturesRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthGuidelinesRoute: typeof AuthGuidelinesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthWaitlistRoute: typeof AuthWaitlistRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthContactRoute: AuthContactRoute,
  AuthFeaturesRoute: AuthFeaturesRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthGuidelinesRoute: AuthGuidelinesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthWaitlistRoute: AuthWaitlistRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardMessagesRouteRouteChildren {
  DashboardMessagesIdRoute: typeof DashboardMessagesIdRoute
  DashboardMessagesIndexRoute: typeof DashboardMessagesIndexRoute
}

const DashboardMessagesRouteRouteChildren: DashboardMessagesRouteRouteChildren =
  {
    DashboardMessagesIdRoute: DashboardMessagesIdRoute,
    DashboardMessagesIndexRoute: DashboardMessagesIndexRoute,
  }

const DashboardMessagesRouteRouteWithChildren =
  DashboardMessagesRouteRoute._addFileChildren(
    DashboardMessagesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardMessagesRouteRoute: typeof DashboardMessagesRouteRouteWithChildren
  DashboardFeedRoute: typeof DashboardFeedRoute
  DashboardInstallRoute: typeof DashboardInstallRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardNotificationRoute: typeof DashboardNotificationRoute
  DashboardPeopleRoute: typeof DashboardPeopleRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSafetyRoute: typeof DashboardSafetyRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMessagesRouteRoute: DashboardMessagesRouteRouteWithChildren,
  DashboardFeedRoute: DashboardFeedRoute,
  DashboardInstallRoute: DashboardInstallRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardNotificationRoute: DashboardNotificationRoute,
  DashboardPeopleRoute: DashboardPeopleRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSafetyRoute: DashboardSafetyRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
